// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvu0GPS3u5yWQ-JuHsmUTYmJDa3QOUVWI',
    appId: '1:912055646294:web:f978a643a330de7d9ee3f7',
    messagingSenderId: '912055646294',
    projectId: 'yoyo-9fb3f',
    authDomain: 'yoyo-9fb3f.firebaseapp.com',
    storageBucket: 'yoyo-9fb3f.firebasestorage.app',
    measurementId: 'G-Q4D5S89XYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_5z0UthtcHKVxx_mSs-YOnya56mMcOwI',
    appId: '1:912055646294:android:e820e8257b5b1d8d9ee3f7',
    messagingSenderId: '912055646294',
    projectId: 'yoyo-9fb3f',
    storageBucket: 'yoyo-9fb3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmdEDmaHxicKWCk89Z6Q1eVqnnpAlNZHE',
    appId: '1:912055646294:ios:0ef21f19d8b0da6a9ee3f7',
    messagingSenderId: '912055646294',
    projectId: 'yoyo-9fb3f',
    storageBucket: 'yoyo-9fb3f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmdEDmaHxicKWCk89Z6Q1eVqnnpAlNZHE',
    appId: '1:912055646294:ios:0ef21f19d8b0da6a9ee3f7',
    messagingSenderId: '912055646294',
    projectId: 'yoyo-9fb3f',
    storageBucket: 'yoyo-9fb3f.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvu0GPS3u5yWQ-JuHsmUTYmJDa3QOUVWI',
    appId: '1:912055646294:web:905d5bd08c579aea9ee3f7',
    messagingSenderId: '912055646294',
    projectId: 'yoyo-9fb3f',
    authDomain: 'yoyo-9fb3f.firebaseapp.com',
    storageBucket: 'yoyo-9fb3f.firebasestorage.app',
    measurementId: 'G-1HH4LJ9YT0',
  );

}